# Generated by Django 6.0.2 on 2026-03-04 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_categorycharacteristic_productcharacteristic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
