# Generated by Django 6.0.2 on 2026-03-04 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_product_full_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='full_description',
        ),
    ]
