# Generated by Django 6.0.2 on 2026-03-04 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_remove_product_full_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcharacteristic',
            options={'ordering': ['characteristic__order', 'characteristic__name'], 'verbose_name': 'Характеристика товара', 'verbose_name_plural': 'Характеристики товара'},
        ),
        migrations.AlterUniqueTogether(
            name='productcharacteristic',
            unique_together=set(),
        ),
    ]
